[package]
name = "img2tempdecal"
version = "4.0.0"
authors = ["Nozomi Miyamori"]
edition = "2021"

[dependencies]
imagequant = { version = "4.3.0", default-features = false }
rgb = "0.8.37"
resize = "0.8.4"

[dev-dependencies]
gif = "0.13.1"
clap = { version = "4.5.4", features = ["derive"] }
