[package]
name = "img2tempdecal"
version = "2.0.0"
authors = ["Nozomi Miyamori"]
edition = "2021"

[dependencies]
imagequant = { version = "4.2.2", default-features = false }
rgb = "0.8.36"
resize = "0.8.2"

[dev-dependencies]
png = "0.17.10"
clap = { version = "4.4.6", features = ["derive"] }
